### ISSUE TITLE
建议：在到期日程前加上课程标题

### ISSUE THREAD

**Issue by hongjr03** [BiDuang/Dolphin#2]
![image](https://github.com/BiDuang/Dolphin/assets/64763790/20b3a5e2-1954-4951-b079-8bdfb899cce1)
如图，建议在日程前加入标题以更好地辨别各个课程喵

**Comment by BiDuang** [comment]
因为目前日程的数据接口都是拉取BB平台生成的ICS日历，然后监视其截止日期并在触发条件时发送邮件。而很遗憾BB平台的这个日历并不会包含学科信息，因此无法提供更多消息捏~ 主要目的就是让你知道有这个作业的存在。
